/**
 * Frozen catalogue of DISTINCT previously-fixed Capture / New Project
 * behaviours. Does not rewrite existing verify scripts. Points at them.
 *
 * Count is behaviours, not asserts.
 */

export type CatalogueEntry = {
  id: string;
  surface: "capture" | "new_project";
  input: string;
  startingState: string;
  expectedInvariant: string;
  historicalDefect: string | null;
  source: string;
};

export const HISTORICAL_BEHAVIOURS: CatalogueEntry[] = [
  {
    id: "existing-person",
    surface: "capture",
    input: "Pippa Gumdrop still UAT lead",
    startingState: "Candyland person-gumdrop",
    expectedInvariant: "no_change / no duplicate person write",
    historicalDefect: "identity gate / duplicate person",
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "new-person",
    surface: "capture",
    input: "Velvet Sprocket joining as paint lead",
    startingState: "Toyworld",
    expectedInvariant: "create_new person; must not retarget Brick/Buttons",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "ambiguous-same-first-name",
    surface: "capture",
    input: "Brick from the warehouse",
    startingState: "Toyworld Brick Oakley",
    expectedInvariant: "Needs You; do not bind Brick Oakley",
    historicalDefect: "D-007",
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "responsibility-continues",
    surface: "capture",
    input: "Pixel Ramos continues as Producer",
    startingState: "GamingStudio5000",
    expectedInvariant: "no_change; no write",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "share-vs-replace-ambiguous",
    surface: "capture",
    input: "Unclear whether Fizz/Pippa share or replace UAT",
    startingState: "Candyland",
    expectedInvariant: "Needs You; never Apply Ready",
    historicalDefect: "D-R10 / D-019",
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "existing-risk-update",
    surface: "capture",
    input: "Packaging delay getting worse",
    startingState: "Toyworld risk-packaging",
    expectedInvariant: "update existing risk; no todo create",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "new-risk",
    surface: "capture",
    input: "Shader compile stalls cert",
    startingState: "GamingStudio5000",
    expectedInvariant: "create_new risk; must not retarget risk-console",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "risk-resolution",
    surface: "capture",
    input: "Gumdrop Bridge icing closed",
    startingState: "Candyland risk-bridge",
    expectedInvariant: "risk status write; not a todo",
    historicalDefect: "Phase 3B domain authority",
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "milestone-move",
    surface: "capture",
    input: "Parade day → 29 Oct 2026",
    startingState: "Candyland ms-parade",
    expectedInvariant: "milestone write; not a todo",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "unchanged-date",
    surface: "capture",
    input: "Track freeze still 1 Sep",
    startingState: "Toyworld ms-freeze",
    expectedInvariant: "no_change",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "todo-create",
    surface: "capture",
    input: "Polish candy-cane banners",
    startingState: "Candyland",
    expectedInvariant: "create_todo",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "availability",
    surface: "capture",
    input: "Fizz away 5–12 Oct",
    startingState: "Candyland person-fizz",
    expectedInvariant: "availability write on existing person",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "duplicate-observation",
    surface: "capture",
    input: "Packaging resolved twice",
    startingState: "Toyworld risk-packaging",
    expectedInvariant: "one write / merge; no duplicate writes",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "pronoun-ambiguity",
    surface: "capture",
    input: "She will own boss balancing",
    startingState: "GamingStudio5000",
    expectedInvariant: "Needs You",
    historicalDefect: "D-007",
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "irrelevant-commentary",
    surface: "capture",
    input: "Lobby chiptunes chatter",
    startingState: "GamingStudio5000",
    expectedInvariant: "commentary only; no writes",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "explicit-no-change",
    surface: "capture",
    input: "Nothing changed on Toyworld",
    startingState: "Toyworld",
    expectedInvariant: "no writes",
    historicalDefect: null,
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "cross-project-bait",
    surface: "capture",
    input: "Pixel/console cert mentioned in Candyland Capture",
    startingState: "Candyland entry",
    expectedInvariant: "Needs You; no foreign writes",
    historicalDefect: "project isolation",
    source: "src/lib/eval-capture-v2/corpus.ts",
  },
  {
    id: "foreign-ids-malformed-envelope",
    surface: "capture",
    input: "Foreign + invented IDs in Candyland envelope",
    startingState: "Candyland",
    expectedInvariant: "reject / fail closed",
    historicalDefect: "foreign_id / cross_project_id",
    source: "src/lib/eval-capture-v2/frozen-model-outputs.ts",
  },
  {
    id: "milestone-date-missing",
    surface: "capture",
    input: "Parade move without date",
    startingState: "Candyland",
    expectedInvariant: "Needs You for date; do not invent today",
    historicalDefect: "missing semantic field",
    source: "e2e/fixtures/capture-results/milestone-date-missing.json",
  },
  {
    id: "sibling-ready-and-needs-you",
    surface: "capture",
    input: "Bridge resolve + share/replace ambiguity",
    startingState: "Candyland",
    expectedInvariant: "Ready sibling stays independent of Needs You sibling",
    historicalDefect: "Review sibling independence",
    source: "e2e/fixtures/capture-results/sibling-ready-and-needs-you.json",
  },
  {
    id: "d033-forged-client-state",
    surface: "capture",
    input: "Analyse with forged client MissionState",
    startingState: "server truth",
    expectedInvariant: "client state ignored",
    historicalDefect: "D-033",
    source: "scripts/verify-capture-server-truth.ts",
  },
  {
    id: "d046-stale-target",
    surface: "capture",
    input: "Apply after entity changed between Analyse and Apply",
    startingState: "fingerprinted expectedTarget",
    expectedInvariant: "Needs You; no write",
    historicalDefect: "D-034 / D-046",
    source: "scripts/verify-capture-server-truth.ts",
  },
  {
    id: "d007-uuid-incomplete-name",
    surface: "capture",
    input: "Incomplete name + model UUID",
    startingState: "person on project",
    expectedInvariant: "Needs You; UUID is not identity proof",
    historicalDefect: "D-007",
    source: "scripts/verify-person-identity-safety.ts",
  },
  {
    id: "aurora-date-move",
    surface: "capture",
    input: "Production release moved 12→19 September",
    startingState: "Aurora ms-production-release",
    expectedInvariant: "update_milestone write",
    historicalDefect: "D-051 diagnostic",
    source: "scripts/verify-capture-intelligence-diagnostic.ts",
  },
  {
    id: "aurora-andris-isolated",
    surface: "capture",
    input: "Andris will take ownership of Legacy",
    startingState: "Aurora Olga+Sarah only",
    expectedInvariant: "Needs You (incomplete recorded name)",
    historicalDefect: "D-051 Lume catch",
    source: "scripts/verify-capture-intelligence-diagnostic.ts",
  },
  {
    id: "aurora-andris-full-paste",
    surface: "capture",
    input: "Andris sentence inside paste that also names Olga and Sarah",
    startingState: "Aurora",
    expectedInvariant: "Needs You (multiple match) — known coupling",
    historicalDefect: "D-051 transcript-wide identity gate",
    source: "scripts/verify-capture-intelligence-diagnostic.ts",
  },
  {
    id: "aurora-pronoun-uat",
    surface: "capture",
    input: "She will own UAT after Olga and Sarah named",
    startingState: "Aurora",
    expectedInvariant: "Needs You",
    historicalDefect: "D-007 / D-051",
    source: "scripts/verify-capture-intelligence-diagnostic.ts",
  },
  {
    id: "np-messy-buckets",
    surface: "new_project",
    input: "Messy Candyland organise observations",
    startingState: "unscoped",
    expectedInvariant: "domain buckets; Pixel is commentary; no invented Objective",
    historicalDefect: "D-032",
    source: "scripts/verify-new-project-v2.ts",
  },
  {
    id: "np-alfresco-four-devs",
    surface: "new_project",
    input: "Olga/Andris/Martins/Elman + Alfresco/PVS/BAU",
    startingState: "unscoped",
    expectedInvariant: "four people stay Needs Review; roles are not responsibilities",
    historicalDefect: "real paste regression",
    source: "scripts/verify-new-project-v2.ts",
  },
  {
    id: "np-olga-sarah-responsibilities",
    surface: "new_project",
    input: "Olga Petrov is responsible for UAT. Sarah Kim is responsible for Release.",
    startingState: "unscoped compose draft",
    expectedInvariant: "scopes survive; Needs You does not re-ask",
    historicalDefect: "Preview #155 / D-051 mapper drop",
    source: "scripts/verify-new-project-v2.ts",
  },
  {
    id: "np-name-only-person",
    surface: "new_project",
    input: "Sarah Murphy with empty responsibilities",
    startingState: "compose",
    expectedInvariant: "name-only Person is complete; no Needs You",
    historicalDefect: "People rules",
    source: "scripts/verify-new-project-four-frame.ts",
  },
  {
    id: "np-informal-name-only-people",
    surface: "new_project",
    input: "bob is the ba / mike handles the legacy builds",
    startingState: "unscoped",
    expectedInvariant: "schema-valid name-only Person observations survive Organise",
    historicalDefect: null,
    source: "scripts/verify-np-organise-observation-loss.ts",
  },
  {
    id: "np-adapter-drops-rejected-observations",
    surface: "new_project",
    input: "Same informal people, extractor near-miss (foreign_id / missing truthIntent / unknown disposition)",
    startingState: "unscoped empty records",
    expectedInvariant:
      "Named people must not silently disappear from /api/new-project after a valid observations envelope",
    historicalDefect: "D-052 New Project adapter maps only validation.observations",
    source: "scripts/verify-np-organise-observation-loss.ts",
  },
  {
    id: "np-knowledge-no-slice",
    surface: "new_project",
    input: "15 distinct Knowledge facts",
    startingState: "compose persist",
    expectedInvariant: "all facts survive hydrate; no .slice(0,12) / .slice(0,24)",
    historicalDefect: "D-049 / D-R44",
    source: "scripts/verify-new-project-four-frame.ts",
  },
  {
    id: "np-duplicate-code",
    surface: "new_project",
    input: "Second project with same code",
    startingState: "workspace codes",
    expectedInvariant: "blocked; no suffix",
    historicalDefect: "D-026",
    source: "scripts/verify-new-project-four-frame.ts",
  },
];

export const DISTINCT_CAPTURE_BEHAVIOURS = HISTORICAL_BEHAVIOURS.filter(
  (row) => row.surface === "capture",
).length;

export const DISTINCT_NEW_PROJECT_BEHAVIOURS = HISTORICAL_BEHAVIOURS.filter(
  (row) => row.surface === "new_project",
).length;
