/**
 * Writes credential-free Playwright fixtures from the frozen V2 pipeline.
 * Not live AI. Regenerated by the eval-foundation verify script.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { experimentalMissionState } from "../src/lib/eval-capture-v2/mission-state";
import { CAPTURE_V2_EVAL_CORPUS } from "../src/lib/eval-capture-v2/corpus";
import { evaluateFrozenCase } from "../src/lib/eval-capture-v2/pipeline";
import { FROZEN_MODEL_OUTPUTS } from "../src/lib/eval-capture-v2/frozen-model-outputs";
import { STACKED_STORIES } from "../src/lib/eval-capture-v2/stacked-stories";

const ROOT = join(process.cwd(), "e2e/fixtures");

function main() {
  mkdirSync(join(ROOT, "capture-results"), { recursive: true });
  writeFileSync(
    join(ROOT, "mission-state.json"),
    JSON.stringify(experimentalMissionState(), null, 2),
  );
  for (const row of FROZEN_MODEL_OUTPUTS) {
    const testCase = CAPTURE_V2_EVAL_CORPUS.find((c) => c.id === row.caseId);
    if (!testCase) continue;
    const evaluated = evaluateFrozenCase(testCase);
    writeFileSync(
      join(ROOT, "capture-results", `${row.caseId}.json`),
      JSON.stringify(
        {
          caseId: row.caseId,
          transcript: testCase.transcript,
          result: evaluated.pipeline.result,
        },
        null,
        2,
      ),
    );
  }
  writeFileSync(
    join(ROOT, "stacked-stories.json"),
    JSON.stringify(STACKED_STORIES, null, 2),
  );
  console.log("Wrote e2e/fixtures from frozen V2 pipeline.");
}

main();
